sudo: true
services:
- docker
language: python
script: make test container
env:
  global:
  - DOCKER_HUB_USERNAME=otakup0pe
  - DOCKER_HUB_EMAIL=jonafree@gmail.com
  - secure: Y8SyIjOuxRT+JpapX1QE04HGW5Jr86n0Z4PtRMLCsnvNvGwF2/KXScPvPkCW+2+/abRkXL6UgbNKyRuBnFouSPFxynDJOr9vgCphu3/3V0J41G2ByIqdO3JjnEN1i3mvIz7K4ymtkcDYed5uEJw7qbFp5xcByEjGNH5x0fcgTcBhaEjB0leOHp+y4UhQadH7AmI0S9PEbuiehx+g0m0e+7cE9eDoQMJRignF7QwcOpCyuEAVjDp1HJuUNcK7Oym5DgXVrJoh/PzVivjzmzgNxSCa8tDIH1MWm5oRTw82bmrgy8J/V1ooN9e28oufNNtQMsPSRDfjJSF/FRGpOazK7D5sf4aSy19sKvsZ9CfKu7/a0ojh7tLHIC3tlOt7UjUrjM7VcUrzwtHF9gNRQkiYrF5dpYgpZ4/iJtEm+Q8Ejrfu/ThlTLg2YvFrNFozT08C8EQgWPjfSYU36BvOvDspCZqNMMgu2eRY9iq73QI/9eoPR5Zy3JnRHms/8DY4/M1p+Ga+AikAnTabUrCV/XqQwFRtVh+WDPFDPoHfwYkKHfoAdCPfRWv/NPMeLrCheLX8Skpt+V24WI1kVrwLhexx9w2JSWuQX1mUQFGJYE7ZzyvJjosQ8mXfUh9bpMAa+5je78vCP93uUpILAFAwISV2XgW/6WhKL6Wv6TevRvLMw8c=
deploy:
  provider: pypi
  user: otakup0pe
  on:
    tags: true
    all_branches: true
    repo: otakup0pe/avakas
  password:
    secure: J/90nkueQZgXWeqDp0gryzTtTOQ7P3Max2+AP3x9ukTUL5hQXJGWAHqIW5J9iJ6TH9CEZW3bO4ivFQi5lnebYgxPKHmlqI0+IJL+Q56onn0d3fVcrifZ04NI311jXiKvPxdVxOd5Hm6jXv7NG3TBaeJHmcJdvuCXWVieGIPA0x79H4IYCDONX3vc+GkDEt0gu/F8O8F2426kcLfuuk6xGFRmQMASCIKSM5LOOpNES1P2QJ/HyEoGSMaM+EGVtuorKvt3GnF1c/aEcFwKMVTGWMtWoPh3nKOidJwk6Y0o+e2hqlIMuK5W9zqO938dtGDEoSkeGC1qW5vwfYiSjT00GbcNd4bP2gxDD4hAygoqe/KG7uVHIjeACw0/pA+eSTtWVNMSMn9oVBbc0eyDbs4PrNB/Pn+smUzxqwYlik5ymSSJ1TjQphGCVZCl8jVtuwjNhzRJxDC8mtJg16oxsE/+I0MPV2LH2yil8LlnbRNu46dou5VbRIYdmTOGbpe88V25GyKCzjDTFV16MHf4E9xCD7jQwnMrBy84bE2NfqNArDHtrVo0fFJjrJv7opEzj3Xln2/+v0mQIXR5DXGgnAAgLX4ABvldDqdZk9NVWl2UEe7mP7ls8hl/qwtDMX6PwAlmlbCyH+V0p99S/JBZb8M7/e2Fcq5IOCfOE/eydz8RCm0=
install:
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
