sudo: true
services:
- docker
language: python
script: make test container
env:
  global:
  - DOCKER_HUB_USERNAME=otakup0pe
  - DOCKER_HUB_EMAIL=jonafree@gmail.com
  - secure: wpZavPBKVcTm8kslE9FXblI9KnB5H1aMFaTnIR+H9zSPBP2L71T3LoVhHO5wBzQxCC8n/AezqVEeONaQDyvRufSyp4p59Jh36ANiTMKBUJKvK2VlzSWm1DnpRpfGjxNMWA5Lpj1EyNVUGcnWucIaZaaOhrfJJE8ZkHPiec4RUnnbYGMumYbn55CaqzcpqjFMUC90mdKr04N4uxIskMdGBLnvxOq2cnC77R1yi0cPzowu69uT6C3E9kvL3oDx5eeRnsxhPu73jCQnoGvfY7p+lb6SkCFRmjeW6ieFzgWO5cvaGxbe9abw56mBZoEsRPehhXJ/ZDyjjNoY0HqIkuJG+8kOoVZhphbeHiE0Z7JlI8J47eUGBkvCSiQEYS92RMD6p452u5sMWEeY1lMNZWMtuPjbdqzu+s391lHfODjY7efiDLdiwsAxKL0tZGlYl3UE7YMAZ/Z8DHf/jclI4Ao4SD03Xpg3UcH6WaV8sp3kgAURdUCs4db6RMfnab1cU2tqRlVUVKXJAn8g/PAxJVXQUg4nh5KaQbXtSwQl792I5yErSUGEDV/Uvy8r+iIcxCghW/mG4KKb+XvcEbB9DNj7rdgG65u9DryLLyNc0jPQIbPBXdy+7MiphDyFvBJZlmlcFsBoULil1JPFTxIb/6E8fb2BgbeQixEUK9A2HjR/tLw=
deploy:
  provider: pypi
  user: otakup0pe
  on:
    tags: true
    all_branches: true
    repo: otakup0pe/avakas
  password:
    secure: J/90nkueQZgXWeqDp0gryzTtTOQ7P3Max2+AP3x9ukTUL5hQXJGWAHqIW5J9iJ6TH9CEZW3bO4ivFQi5lnebYgxPKHmlqI0+IJL+Q56onn0d3fVcrifZ04NI311jXiKvPxdVxOd5Hm6jXv7NG3TBaeJHmcJdvuCXWVieGIPA0x79H4IYCDONX3vc+GkDEt0gu/F8O8F2426kcLfuuk6xGFRmQMASCIKSM5LOOpNES1P2QJ/HyEoGSMaM+EGVtuorKvt3GnF1c/aEcFwKMVTGWMtWoPh3nKOidJwk6Y0o+e2hqlIMuK5W9zqO938dtGDEoSkeGC1qW5vwfYiSjT00GbcNd4bP2gxDD4hAygoqe/KG7uVHIjeACw0/pA+eSTtWVNMSMn9oVBbc0eyDbs4PrNB/Pn+smUzxqwYlik5ymSSJ1TjQphGCVZCl8jVtuwjNhzRJxDC8mtJg16oxsE/+I0MPV2LH2yil8LlnbRNu46dou5VbRIYdmTOGbpe88V25GyKCzjDTFV16MHf4E9xCD7jQwnMrBy84bE2NfqNArDHtrVo0fFJjrJv7opEzj3Xln2/+v0mQIXR5DXGgnAAgLX4ABvldDqdZk9NVWl2UEe7mP7ls8hl/qwtDMX6PwAlmlbCyH+V0p99S/JBZb8M7/e2Fcq5IOCfOE/eydz8RCm0=
install:
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
